global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/alert_rules.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: bentoml-fraud
    metrics_path: /metrics
    static_configs:
      - targets: ["bentoml-fraud:7001"]

  - job_name: bentoml-pricing
    metrics_path: /metrics
    static_configs:
      - targets: ["bentoml-pricing:7002"]

  - job_name: mlflow
    metrics_path: /metrics
    static_configs:
      - targets: ["mlflow:5000"]

  - job_name: airflow-webserver
    metrics_path: /metrics
    static_configs:
      - targets: ["airflow-webserver:8080"]

